version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg_cinematics
    environment:
      POSTGRES_DB: pg_cinematicsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_NAME: pg_cinematicsDB
      DB_USER: admin
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true 
    #restart: always

volumes:
  db_data:
